visualizer:
  max_views: 15000 #80
  min_gain: 10
  downsample: 10  # 10/20 for sim/hw respectively
  base_frame_id: map
  ee_grasp_offset: [0.0, 0.0, -0.383, 0.924, 0.0, 0.0, 0.065]  # offset to panda_link8

  camera:
    min_z_dist: 0.3
    info_topic: /my_temoto/robot_manager/robots/vaultbot_sim/camera/depth/camera_info
    frame_id: camera_link_dummy

vgn:
  qual_threshold: 1.1 #0.9
  model: /home/srinath/Documents/Master/temoto_ws/src/vgn/assets/models/vgn_conv.pth   #$(find vgn)/assets/models/vgn_conv.pth
  finger_depth: 0.05

policy:
  rate: 4
  window_size: 12

nbv_grasp:
  max_views: 15000 #80
  min_gain: 10
  downsample: 10  # 10/20 for sim/hw respectively